server:
  port: 8000
spring:
  redis:
    host: 192.168.188.146
    port: 6379
    password: offcn123
  session:
    store-type: redis # 设置session保存的位置
    timeout: 1800 #设置过期时间 单位秒
  #开始thymeleaf设置
  thymeleaf:
      #禁用模板缓存
    cache: false


